export const titles = {
  viewMenu: 'Ver Negocios',
  addMenu: 'Agregar Negocio',
  addUser: 'Agregar Usuario',
  addUserCourse: 'Agregar Usuario a Curso',
  addModule: 'Agregar Módulo',
  moduleText: 'Módulo',
  maduleDescription: 'Descripción: ',
  mediaLabel: 'Material Multimedia',
  fileLabel: 'Archivo',
  videoLabel: 'Video',
  playLabel: 'Play',
  editModule: 'Editar Módulo',
  deleteModule: 'Eliminar Módulo',
  exportMenu: 'Exportar Negocios',
  importMenu: 'Importar Negocios',
  actions: 'Acciones',
  rowsPerPage: 'Registros máximos',
  modalCreate: 'Crear Negocio',
  modalEdit: 'Editar Negocio',
  modalDelete: 'Eliminar Negocio',
  modaleDeleteDetail: 'Seguro que desea eliminar el negocio: ',
  modalCreateModule: 'Crear Módulo',
  modalEditModule: 'Editar Módulo',
  modalDeleteModule: 'Eliminar Módulo',
  modaleDeleteModule: 'Seguro que desea eliminar el módulo: ',
  noRecordsYet: 'No existen negocios aún!',
  noRecordsModulesYet: 'No existen módulos aún!',
  noRecordsRegisteredYet: 'No existen usuarios matriculados aún!',
  loadingUsers: 'Cargando información de usuarios...',
  buttonCreate: 'Crear',
  buttonAdd: 'Agregar',
  buttonSave: 'Guardar',
  buttonEdit: 'Editar',
  buttonDelete: 'Eliminar',
  buttonCancel: 'Cancelar',
  buttonClose: 'Cerrar',
  buttonExport: 'Exportar',
  buttonImport: 'Importar',
  buttonAddUser: 'Matricular',
  imageUploadTitle: 'Cargar Archivo',
  imageUploadButton: 'Seleccione un archivo PDF, WORD, PPT...',
  videoUploadButton: 'Seleccione un archivo de video...',
  addUserRegistered: 'Matricular Usuario',
  previewOwner: 'Tutor: ',
  previewDuration: 'Duración: ',
  instructionsImg: 'Click en la imagen para cambiarla',
  logoImg: 'Logotipo',
  addUserCourseTitle: 'Usuarios Matriculados en ',
  searchLabel: 'Buscar Usuario: ',
  placeholderSearch: 'Buscar por Nombre o Correo',
  tableCell1: 'Nombre',
  tableCell2: 'Email',
  tableActions: 'Acciones',
  maxRecords: 'Registros máximos',
  banner: 'Portada',
  lastday: 'Es tu último día de membresía, renueva tu subscripción!'
};

export const inputLabels = {
  id: 'Identificativo del negocio',
  name: 'Nombre del Negocio',
  owner: 'Responsable',
  description: 'Descripción',
  webPage: 'Página Web',
  phone: 'Teléfono',
  email: 'Correo',
  province: 'Provincia',
  city: 'Ciudad',
  address: 'Dirección',
  logo: 'Logotipo del negocio',
  image: 'Imagen ',
  facebook: 'Link de Facebook',
  instagram: 'Link de Instagram',
  youtube: 'Link de Youtube',
  telegram: 'Link de Telegram',
  search: 'Buscar por nombre de negocio',
  validation: 'Puedes registrar hasta 3 negocios!'
};
