export const titles = {
  addMenu: 'Agregar Cliente',
  exportMenu: 'Exportar Clientes',
  importMenu: 'Importar Clientes',
  actions: 'Acciones',
  rowsPerPage: 'Registros máximos',
  modalCreate: 'Crear Cliente',
  modalEdit: 'Editar Cliente',
  modalDelete: 'Eliminar Cliente',
  modaleDeleteDetail: 'Seguro que desea eliminar al cliente: ',
  noRecordsYet: 'No existen clientes aún!',
  buttonCreate: 'Crear',
  buttonEdit: 'Editar',
  buttonDelete: 'Borrar',
  buttonCancel: 'Cancelar',
  buttonClose: 'Cerrar',
  buttonExport: 'Exportar',
  buttonImport: 'Importar'
};

export const inputLabels = {
  labelType: 'Tipo de Documento',
  type: 'type',
  labelName: 'Nombre / Razón Social',
  name: 'name',
  labelCi: 'C.I. / R.U.C.',
  ci: 'ci',
  labelContact: 'Contacto',
  contact: 'contact',
  labelAddress: 'Dirección',
  address: 'address',
  labelEmail: 'E-mail',
  email: 'email',
  labelPhone: 'Teléfono',
  phone: 'phone',
  labelCity: 'Ciudad',
  city: 'city',
  labelObservations: 'Observaciones',
  observations: 'observationes',
  labelBirth: 'Fecha de Nacimiento',
  birth: 'birth',
  placeHolderSearch: 'Buscar por Razón Social o C.I. / R.U.C.',
  search: 'search'
};
