export const titles = {
  viewMenu: 'Ver Cursos',
  addMenu: 'Agregar Curso',
  addUser: 'Agregar Usuario',
  addUserCourse: 'Agregar Usuario a Curso',
  addModule: 'Agregar Módulo',
  moduleText: 'Módulo',
  maduleDescription: 'Descripción: ',
  mediaLabel: 'Material Multimedia',
  fileLabel: 'Archivo',
  videoLabel: 'Video',
  playLabel: 'Play',
  editModule: 'Editar Módulo',
  deleteModule: 'Eliminar Módulo',
  exportMenu: 'Exportar Curso',
  importMenu: 'Importar Curso',
  actions: 'Acciones',
  rowsPerPage: 'Registros máximos',
  modalCreate: 'Crear Curso',
  modalEdit: 'Editar Curso',
  modalDelete: 'Eliminar Curso',
  modaleDeleteDetail: 'Seguro que desea eliminar el curso: ',
  modalCreateModule: 'Crear Módulo',
  modalEditModule: 'Editar Módulo',
  modalDeleteModule: 'Eliminar Módulo',
  modaleDeleteModule: 'Seguro que desea eliminar el módulo: ',
  noRecordsYet: 'No existen cursos aún!',
  noRecordsModulesYet: 'No existen módulos aún!',
  noRecordsRegisteredYet: 'No existen usuarios matriculados aún!',
  loadingUsers: 'Cargando información de usuarios...',
  buttonCreate: 'Crear',
  buttonAdd: 'Agregar',
  buttonSave: 'Guardar',
  buttonEdit: 'Editar',
  buttonDelete: 'Eliminar',
  buttonCancel: 'Cancelar',
  buttonClose: 'Cerrar',
  buttonExport: 'Exportar',
  buttonImport: 'Importar',
  buttonAddUser: 'Matricular',
  imageUploadTitle: 'Cargar Archivo',
  imageUploadButton: 'Seleccione un archivo PDF, WORD, PPT...',
  videoUploadButton: 'Seleccione un archivo de video...',
  addUserRegistered: 'Matricular Usuario',
  previewOwner: 'Tutor: ',
  previewDuration: 'Duración: ',
  instructionsImg: 'Click en la imagen para cambiarla',
  addUserCourseTitle: 'Usuarios Matriculados en ',
  searchLabel: 'Buscar Usuario: ',
  placeholderSearch: 'Buscar por Nombre o Correo',
  tableCell1: 'Nombre',
  tableCell2: 'Email',
  tableActions: 'Acciones',
  maxRecords: 'Registros máximos',
  banner: 'Portada'
};

export const inputLabels = {
  id: 'Identificativo del curso',
  owner: 'Instructor del curso',
  name: 'Nombre del curso',
  description: 'Descripción del curso',
  image: 'Imagen del curso',
  rating: 'Reseñas',
  duration: 'Número de horas',
  number: 'Número de módulos',
  price: 'Precio',
  language: 'Idioma (ESP, ENG)',
  search: 'Buscar por nombre de curso',
  detail: 'Detalle',
  link: 'Link Video',
  title: 'Título',
  subtitle: 'Sub título'
};
