export const titles = {
  addMenu: 'Agregar Beneficio',
  exportMenu: 'Exportar Beneficio',
  importMenu: 'Importar Beneficio',
  actions: 'Acciones',
  rowsPerPage: 'Registros máximos',
  modalCreate: 'Crear Beneficio',
  modalEdit: 'Editar Beneficio',
  modalDelete: 'Eliminar Beneficio',
  modaleDeleteDetail: 'Seguro que desea eliminar el Beneficio: ',
  noRecordsYet: 'No existen beneficios aún!',
  buttonCreate: 'Crear',
  buttonEdit: 'Editar',
  buttonDelete: 'Borrar',
  buttonAccept: 'Generar',
  buttonCancel: 'Cancelar',
  buttonClose: 'Cerrar',
  buttonExport: 'Exportar',
  buttonImport: 'Importar'
};

export const inputLabels = {
  labelType: 'Tipo de Documento',
  type: 'type',
  labelName: 'Nombre / Razón Social',
  name: 'name',
  labelCi: 'C.I. / R.U.C.',
  ci: 'ci',
  labelContact: 'Contacto',
  contact: 'contact',
  labelAddress: 'Dirección',
  address: 'address',
  labelEmail: 'E-mail',
  email: 'email',
  labelPhone: 'Teléfono',
  phone: 'phone',
  labelCity: 'Ciudad',
  city: 'city',
  labelObservations: 'Observaciones',
  observations: 'observationes',
  labelBirth: 'Fecha de Nacimiento',
  birth: 'birth',
  placeHolderSearch: 'Buscar por usuario',
  placeHolderAmount: 'Monto a procesar',
  search: 'search',
  orderValue: 'Ingrese el monto que desea procesar!'
};
