export const titles = {
  require: 'Todos los campos marcados con * son obligatorios.!',
  title: 'Validación de Comprobantes',
  titleActivation: 'Activación de Suscripción',
  successCreate: 'Comprobante creado correctamente!.',
  successUpdate: 'Comprobante actualizado correctamente!.',
  successDelete: 'Comprobante inactivado correctamente!.',
  titleDeleteModal: 'Seguro que desea eliminar al Comprobante: ',
  titleActivationModal: 'Esta seguro que desea activar una suscripción?',
  titleCreate: 'Crear Comprobante',
  titleUpdate: 'Editar Comprobante',
  titleDelete: 'Inactivar Comprobante',
  titleVoucher: 'Validación de Comprobantes',
  labelCreate: 'Comprobante creado',
  labelUpdate: 'Comprobante actualizado',
  labelDelete: 'Comprobante inactivado',
  generalError: 'Ups algo salio mal: ',
  generalAction: 'Acciones',
  menuCreate: 'Agregar Comprobante',
  tableCell1: 'Id',
  tableCell2: 'Usuario',
  tableCell3: 'Email Usuario',
  tableCell4: 'Fecha',
  tableCellActions: 'Acciones',
  maxRecords: 'Registros máximos',
  noRecordsFound: 'No existen comprobantes aún!',
  buttonCreate: 'Crear',
  buttonUpdate: 'Actualizar',
  buttonDelete: 'Inactivar',
  buttonCancel: 'Cancelar',
  buttonDownload: 'Descargar',
  buttonActive: 'Activar',
  loading: 'Cargando...',
  level1: 'Nivel 1',
  level2: 'Nivel 2',
  level3: 'Nivel 3',
  level4: 'Nivel 4',
  active: 'MIEMBRO',
  noActive: 'NO MIEMBRO',
  altImage: 'Avatar user'
};

export const inputLabels = {
  search: 'searchField',
  name: 'name',
  labelName: 'Nombre',
  lastName: 'lastName',
  labelLastName: 'Apellido',
  email: 'email',
  labelEmail: 'E-mail',
  profile: 'profile',
  labelProfile: 'Perfil',
  state: 'State',
  labelState: 'Estado',
  placeHolderSearch: 'Buscar por número de comprobante, Nombre o Correo electrónico'
};
